name: 'pr'

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.ref }}

jobs:
  test:
    name: Teste
    runs-on: ubuntu-latest
    steps:
      - run: sleep 150
