name: Release to PROD

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Which aplication to release to PROD environment?
        options:
          - App test
        required: true

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'
      - run: git tag v1.0.2
      - run: git push origin v1.0.2
      - run: yarn install
      
      - run: yarn release
        env:
          GH_TOKEN: ${{ secrets.COMMIT_KEY }}
